name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - fix
      - bugfix
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore
      - debug
      - refactor
      - docs
      - Testing
  - title: '🏗️ CI'
    labels:
      - CI
      - devops
  - title: '📖 Docs'
    labels:
      - documentation
      - docs
  - title: '🔗 Dependencies'
    labels:
      - dependencies
      - dependabot
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## ❓ Uncategorized Changes

  $CHANGES
